version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: '01:00'
    reviewers:
      - sonallux
    groups:
      docusaurus:
        patterns:
          - "@docusaurus/*"
      chart-js:
        patterns:
          - "chart.js"
          - "chartjs-plugin-annotation"
          - "react-chartjs-2"
      react:
        patterns:
          - "react"
          - "react-dom"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
      time: '02:00'
    reviewers:
      - sonallux
