/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

async function sidebarItemsGenerator({
  defaultSidebarItemsGenerator,
  ...args
}) {
  const sidebarItems = await defaultSidebarItemsGenerator(args);
  return [
    ...sidebarItems,
    {
      type: 'link',
      label: 'All Tags',
      href: '/docs/tags',
    },
  ];
}

module.exports = {sidebarItemsGenerator, sidebars};
